language: node_js
node_js: node
services:
- mongodb

deploy:
  provider: heroku
  api_key:
    secure: paGLgwt3khGz2yuNfzvb
  app: immense-hollows-35075
  on:
    repo: Daniel-Slabaugh/blog-app-mongoose-challenge-solution